---

- name: 'CONFIG | Generate locale configuration file'
  template:
    src: "{{ role_path }}/templates/locale.j2"
    dest: "{{ locales_config_file_dest }}"
    owner: "{{ locales_config_file_owner }}"
    group: "{{ locales_config_file_group }}"
    mode: "{{ locales_config_file_mode }}"


- name: 'CONFIG | Generate locale.gen configuration file'
  template:
    src: "{{ role_path }}/templates/locale.gen.j2"
    dest: "{{ locales_gen_file_dest }}"
    owner: "{{ locales_config_file_owner }}"
    group: "{{ locales_config_file_group }}"
    mode: "{{ locales_config_file_mode }}"


- name: 'CONFIG | Generate locales'
  locale_gen:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  register: 'locale_generated'
  with_items: "{{ locales_to_configure }}"


- name: 'CONFIG | Update system settings'
  command: "{{ locales_update_command }}"
  when: 'locale_generated.changed or (locale_language_packs.changed | default(False))'
