---

- name: 'CONFIG | Generate locale configuration file'
  template:
    src: "{{ role_path }}/templates/locale.j2"
    dest: "{{ locales_config_file_dest }}"
    owner: "{{ locales_config_file_owner }}"
    group: "{{ locales_config_file_group }}"
    mode: "{{ locales_config_file_mode }}"


- name: 'CONFIG | Generate locale.gen configuration file'
  template:
    src: "{{ role_path }}/templates/locale.gen.j2"
    dest: "{{ locales_gen_file_dest }}"
    owner: "{{ locales_config_file_owner }}"
    group: "{{ locales_config_file_group }}"
    mode: "{{ locales_config_file_mode }}"


- name: 'CONFIG | Generate locales on Debian family'
  locale_gen:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | Update system settings'
  when: (ansible_os_family | lower) != 'redhat'
  with_items: "{{ locales_to_configure }}"


- name: 'CONFIG | Generate locales on RedHat family'
  command: >
    localedef
    -c
    -f {{ item.name.split('.')[1] }}
    -i {{ item.name.split('.')[0] }}
    {{ item.name }}
  changed_when: False
  notify: 'HANDLER | Update system settings'
  when: (ansible_os_family | lower) == 'redhat'
  with_items: "{{ locales_to_configure }}"
