---

# Main tasks file for locales role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::locales'
    - 'role::locales::init'


- name: 'INSTALL | Manage installation tasks'
  include: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  become: True
  tags:
    - 'role::locales'
    - 'role::locales::install'


- name: 'CONFIG | Manage configuration tasks'
  include: "{{ role_path }}/tasks/config.yml"
  become: True
  tags:
    - 'role::locales'
    - 'role::locales::config'
